version: '3'

services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: jekyll-site
    environment:
      - JEKYLL_ENV=development
    command: jekyll serve --watch --force_polling --verbose --livereload
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    stdin_open: true
    tty: true
